### ISSUE TITLE
Doesn't work on .vbb files.

### ISSUE THREAD

**Issue by Arc2019** [simonzachau/caltech-pedestrian-dataset-to-yolo-format-converter#2]
I want to extract labels from KAIST Multispectral Pedestrian Detection Dataset, which provides .vbb files in YOLO format. the given code does not seem to work.

**Comment by simonzachau** [comment]
As explained in the Readme, the code is intended to be used to convert the [Caltech Pedestrian Dataset](http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/). Likely, the .vbb files of your dataset use a different schema. If you have any questions regarding that matter, please ask them specifically. Please feel free to adapt the code to your needs.
