### ISSUE TITLE
Effecting the annotation

### ISSUE THREAD

**Issue by shivam1423** [simonzachau/caltech-pedestrian-dataset-to-yolo-format-converter#4]
By changing the dimension of the image will it not affect the origin annotation?

**Comment by simonzachau** [comment]
The annotations are calculated in the function `convertBoxFormat` in `generate-annotation.py`. By setting the variable `squared` to true, the relative position is calculated based on the new height. If you have doubts about the implementation or about how this is interpreted by YOLOv2, please explain so I can follow up.
